### ISSUE TITLE
Custom-Team-Chat-Color Not working.

### ISSUE THREAD

**Issue by MrTokyo12345** [MetallicGoat/MBedwarsTweaks#17]
Custom-Team-Chat-Color:
it doesn't seem to work, i set a different color but my config doesn't change it

#Change default team chat colors
#Add teams like: "DefaultTeamName:ChatColorCar"
Custom-Team-Chat-Color:
  Enabled: true
  Teams:
    - 'BLUE:9'
   
    MBedwarsTweaks-3.0.1-Dev-B.jar
    MBedWars 5.2.3
    Server jar:  FlamePaper (1.0.3) for 1.8.8 by LinsaFTW.

**Comment by MetallicGoat** [comment]
Well you are trying to change the teams color to the same color so obviously there would be no difference. Also in the latest version I believe we switched to using the color name, rather than the char.

**Comment by MrTokyo12345** [comment]
Yes, MBedWars by default for blue uses &1, but I would like to put &9

**Comment by MetallicGoat** [comment]
Ok so I looked into it. The reason it is not working for you is because you are putting the ChatColor character (char). The comment says thats what you are supposed to do, but that was changed in v3.0.0, and I forgot to update the comment. 

I have a feeling you are not actually using v3.0.0 though, because the syntax should be this:

```yml
# Change default team chat colors
# Add teams like: "DefaultTeamName: ChatColor"
Custom-Team-Colors-Enabled: false
Custom-Team-Colors:
  CYAN: dark_aqua
```
